### ISSUE TITLE
Make 6 recipes

### ISSUE THREAD

**Issue by kevinrue** [iSEE/iSEEWorkshopEuroBioc2020#1]
- Recipe = screenshot of an app state we'd like participants to reach
- Give a hint
- First solution is click and point way.
- Fully programmatical solution

### Panel organisation

- [x] Add and remove panels, e.g. "Create an app that has only panel X and Y".

### Configure data parameters

- [x] Visualise the cell type assignment against cluster membership, to identify the predominant cell type in each cluster, i.e., A Hinton plot
- [x] Make an app that open with 2 RedDimPlot panels, with different dimensionality reduction selected.
- [x] Show the expression of CD74 across cell types.

### Visual parameters

- [x] Make an app that open with 2 RedDimPlot panels, colored by either cluster or cell type
- [x] Make an app that open with 2 RedDimPlot panels, colored by the expression of two different genes
- [x] Reduce the point size and opacity of points to suitable values for the size of this data set.

### Panel specific

- [x] Use the expression of genes to validate the present of known cell populations (e.g. CD79A and CD74 to identify B-cells;  CD3D and CD74 to identify T-cells)

### Selection

- [x] Create an app that links panels through selections.

### Tour

- [x] Create a little story on the standard configuration

**Comment by csoneson** [comment]
- [x] Add a general pointer to where to read more about the different panel types (such as the respective slots) in exercise 1. -> man pages
- [x] Add a figure with the relationship between the different panel classes
- [x] Add an exercise involving `iSEEu`? E.g., modes, or non-default panels

**Comment by csoneson** [comment]
All boxes checked, closing :)
